### ISSUE TITLE
scala.ScalaReflectionException: object macroid.warts.CheckUi not found

### ISSUE THREAD

**Issue by aregic** [macroid/macroid-akka-pingpong#5]
Same as: https://github.com/macroid/macroid-akka-pingpong/issues/1

I created the project via activator template, and I'm simply trying to compile it as it is. android-sdk-plugin version is 1.3.6. Nothing in the linked threads seems to make any difference, I always get the same error.

Before compiling fails, there are some warnings that might help:

[warn] Scala version was updated by one of library dependencies:
[warn] 	* org.scala-lang:scala-library:(2.11.1, 2.11.4, 2.11.2, 2.11.0) -> 2.11.6
[warn] To force scalaVersion, add the following:
[warn] 	ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.android.support:support-v4:21.0.3 -> 22.1.1

**Comment by stanch** [comment]
Hey, the simplest solution for now is to remove these lines: https://github.com/macroid/macroid-akka-pingpong/blob/master/build.sbt#L17-L20. See also the discussion at https://groups.google.com/forum/#!topic/macroid/Xt8V16BoM3w.

I will try to look into it soon to see what the proper way to fix this is.

**Comment by aregic** [comment]
Hello!

Thank you! The error above doesn't show up anymore, but I have a new one:
java.lang.UnsupportedClassVersionError: macroid/LayoutTweakMacros$ : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at java.lang.Class.forName0(Native Method)
        ...

Maybe I should create a separate issue about this but most likely everyone who will start building this project will go through the same steps, so I leave this choice to you.

**Comment by stanch** [comment]
The error seems to be that something in your toolchain does not support Java 7. Do you have JDK 6 installed? Or maybe an outdated version of Android Build Tools (unlikely)?

**Comment by aregic** [comment]
I have openjdk7. I tryed to remove the openjdk6 just to be sure, tryed updating the android build tools, neither helped so far, same error.

**Comment by aregic** [comment]
I have reverted the last pull request (87d3b713) locally and set the source and target version of java to 1.6 in build.sbt and now it works.

**Comment by stanch** [comment]
As far as I remember, Macroid `M3` was built with Java `1.6`, so at least the behavior is consistent. However I’m not sure why your toolchain requires `1.6`. Maybe @pfn has an idea?

**Comment by pfn** [comment]
The stack trace is elided, so can't tell what tool is failing. Usually dex fails with that error, so it would indicate build tools being out of date.

**Comment by aregic** [comment]
Ok, I have solved the second issue too: I have installed the official oracle JDK. Other scala -> android libraries refused to work on openJDK too, so the conclusion: don't use openJDK in scala -> android tool chains, only oracle JDK works (I'm using debian linux).
